### ISSUE TITLE
Problem with the requirements in the readme

### ISSUE THREAD

**Issue by RegisGraptin** [JulienCHATEAU/Ymaets#1]
Hello,

I just follow the instruction of the README.md. 
When I try with go to get the raylib library, I got an error.
I don't know if you know how to handle this error. 

Version of go :

`go version go1.10.4 linux/amd64`

Command : 
`go get -v -u $GOPATH/src/github.com/gen2brain/raylib-go/raylib`

Error :
`package /tmp/game/go/src/github.com/gen2brain/raylib-go/raylib: unrecognized import path "/tmp/game/go/src/github.com/gen2brain/raylib-go/raylib" (import path does not begin with hostname)`

Best regards

**Comment by JulienCHATEAU** [comment]
Hello,

Can you run these commands to help me debugging and send me the output :
`go env`
`echo $GOROOT`

Thank you :)

**Comment by RegisGraptin** [comment]
> go env 

```
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/rere/.cache/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/tmp/game/go"
GORACE=""
GOROOT="/usr/lib/go-1.10"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go-1.10/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build406050249=/tmp/go-build -gno-record-gcc-switches"

```

> echo $GOROOT

I have no result for this one.

**Comment by JulienCHATEAU** [comment]
Your Go environment variables are correct.

Try to run these commands to install some dependencies required by Raylib I didn't mentioned : 
`apt-get install libgl1-mesa-dev libxi-dev libxcursor-dev libxrandr-dev libxinerama-dev`
`apt-get install libgl1-mesa-dev libwayland-dev libxkbcommon-dev`

Then try to run again `go get -v -u $GOPATH/src/github.com/gen2brain/raylib-go/raylib`

**Comment by RegisGraptin** [comment]
I do the installation but I get again the same error :

`package /tmp/game/go/src/github.com/gen2brain/raylib-go/raylib: unrecognized import path "/tmp/game/go/src/github.com/gen2brain/raylib-go/raylib" (import path does not begin with hostname)
`

**Comment by JulienCHATEAU** [comment]
Have you upgrade you packages ?
`sudo apt update`
`sudo apt upgrade`

**Comment by RegisGraptin** [comment]
I have and get always the same error :(

**Comment by JulienCHATEAU** [comment]
Is now you go version to the latest one being 1.14 ?

**Comment by RegisGraptin** [comment]
No my version is still 1.10.
But I decided to re-install all the go package.
And I see that I have two path for the go :
/usr/lib/go - 1.10
/usr/local/go - 1.14
I used the last one and I finally succeed to install all the requirements for playing the game ;)  

Thank you for your help :)
